[package]
name = "lidy"
version = "0.1.0"
edition = "2021"

[dependencies]
lidy__yaml = { path = "yaml", version = "0.1.0" }
yaml-rust = "0.4"
regex = "1.9"
lazy_static = "1.4"
chrono = "0.4.39"

[dev-dependencies]
regex = "1.11.1"
specimen = { path = "../../specimen/rust", version = "0.1.0" }
