on: push
name: Test-and-build
jobs:
  checks:
    name: run tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.1"
      - working-directory: ./go/lidy
        run: go test
